ln -s ../../../../repo_submodules/aapFunctionalCluster_CommunicationManagement/main_LATEST                 aapFunctionalCluster_CommunicationManagement
ln -s ../../../../repo_submodules/aapFunctionalCluster_Core/main_LATEST                                    aapFunctionalCluster_Core
ln -s ../../../../repo_submodules/aapFunctionalCluster_Cryptography/main_LATEST                            aapFunctionalCluster_Cryptography
ln -s ../../../../repo_submodules/aapFunctionalCluster_DiagnosticManagement/pProjectVirtualEcu_LATEST      aapFunctionalCluster_DiagnosticManagement
ln -s ../../../../repo_submodules/aapFunctionalCluster_ExecutionManagement/main_LATEST                     aapFunctionalCluster_ExecutionManagement
ln -s ../../../../repo_submodules/aapFunctionalCluster_Firewall/main_LATEST                                aapFunctionalCluster_Firewall
ln -s ../../../../repo_submodules/aapFunctionalCluster_IntrusionDetectionSystemManager/main_LATEST         aapFunctionalCluster_IntrusionDetectionSystemManager
ln -s ../../../../repo_submodules/aapFunctionalCluster_LogAndTrace/main_LATEST                             aapFunctionalCluster_LogAndTrace
ln -s ../../../../repo_submodules/aapFunctionalCluster_NetworkManagement/main_LATEST                       aapFunctionalCluster_NetworkManagement
ln -s ../../../../repo_submodules/aapFunctionalCluster_Persistency/main_LATEST                             aapFunctionalCluster_Persistency
ln -s ../../../../repo_submodules/aapFunctionalCluster_PlatformHealthManagement/main_LATEST                aapFunctionalCluster_PlatformHealthManagement
ln -s ../../../../repo_submodules/aapFunctionalCluster_RawDataStream/main_LATEST                           aapFunctionalCluster_RawDataStream
ln -s ../../../../repo_submodules/aapFunctionalCluster_Registry/main_LATEST                                aapFunctionalCluster_Registry
ln -s ../../../../repo_submodules/aapFunctionalCluster_StateManagement/main_LATEST                         aapFunctionalCluster_StateManagement
ln -s ../../../../repo_submodules/aapFunctionalCluster_TimeSynchronization/main_LATEST                     aapFunctionalCluster_TimeSynchronization
ln -s ../../../../repo_submodules/aapFunctionalCluster_UpdateAndConfigurationManagement/main_LATEST        aapFunctionalCluster_UpdateAndConfigurationManagement
ln -s ../../../../repo_submodules/aapFunctionalCluster_VehicleUpdateAndConfigurationManagement/main_LATEST aapFunctionalCluster_VehicleUpdateAndConfigurationManagement
ln -s ../../../../repo_submodules/common/main_LATEST                                                       common
ln -s ../../../../repo_submodules/SwcApplControlMotor/b_calcFloatingPoint                                  SwcApplControlMotor
ln -s ../../../../repo_submodules/SwcApplDigitalTwinMotorPMSM/b_calcFloatingPoint                          SwcApplDigitalTwinMotorPMSM
ln -s ../../../../repo_submodules/SwcServiceEcuM/main_LATEST                                               SwcServiceEcuM
ln -s ../../../../repo_submodules/SwcServiceEthTp/pProjectVirtualEcu_LATEST                                SwcServiceEthTp
