load(
      "@rules_cc//cc:defs.bzl"
   ,  "cc_binary"
)

cc_binary(
      name = "pProjectFull_main_LATEST"
   ,  deps = [
            "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_CommunicationManagement"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_Core"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_Cryptography"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_DiagnosticManagement"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_ExecutionManagement"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_Firewall"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_IntrusionDetectionSystemManager"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_LogAndTrace"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_NetworkManagement"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_Persistency"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_PlatformHealthManagement"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_RawDataStream"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_Registry"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_StateManagement"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_TimeSynchronization"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_UpdateAndConfigurationManagement"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/aapFunctionalCluster_VehicleUpdateAndConfigurationManagement"
      ]
)

