load(
      "@rules_cc//cc:defs.bzl"
   ,  "cc_binary"
)

cc_binary(
      name = "pProjectFull_main_LATEST"
   ,  deps = [
            "//repo_projects/pProjectFull/main_LATEST/source/SwcServiceStartup:SwcServiceStartup"
         ,  "//repo_projects/pProjectFull/main_LATEST/source/SwcServiceEcuM:SwcServiceEcuM"
      ]
)

