load(
      "@rules_cc//cc:defs.bzl"
   ,  "cc_binary"
)

cc_binary(
      name = "pProjectFull_vR0.0.3"
   ,  deps = [
            "//repo_projects/pProjectFull/vR0.0.3/source/SwcServiceStartup:SwcServiceStartup"
         ,  "//repo_projects/pProjectFull/vR0.0.3/source/SwcServiceEcuM:SwcServiceEcuM"
         ,  "//repo_projects/pProjectFull/vR0.0.3/source/SwcServiceOs:SwcServiceOs"
      ]
)

